export default [
    {text: 'TlGridTemplate', compPath: 'grid-template/index', code: 'TlGridTemplate'},
    {text: 'DragResizeBox', compPath: 'drag-box/index', code: 'DragResizeBox'},
    {text: 'Overlap', compPath: 'demo/overlap', code: 'Overlap'},
    {text: 'Cherry Down', compPath: 'demo/cherry-down', code: 'CherryDown'},
    {text: 'Grid Layout', compPath: 'demo/grid-layout', code: 'GridLayout'},
    {text: 'My Window', compPath: 'demo/my-window', code: 'MyWindow'},
    {text: 'Slider', compPath: 'demo/slider', code: 'Slider'},
    {text: 'Photo Wall', compPath: 'demo/photo-wall', code: 'PhotoWall'},
    {text: 'Rotate', compPath: 'demo/rotate', code: 'Rotate'},
    {text: 'Player Guider', compPath: 'demo/player-guider', code: 'PlayerGuider'},
    {text: 'Three JS', compPath: 'three/index', code: 'ThreeJS'},
    {text: 'Test Drag', compPath: 'test-drag/index', code: 'TestDrag'},
    {text: 'Draw Board', compPath: 'canvas/DrawBoard', code: 'DrawBoard'},
];